export const Locations = [
    {
        id:3,
        name:'Lenora Barrett',
        category:'tobacco',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'rising ocean dot break growth pencil failed river plus farmer truth fort eleven aid original relate80.5033d guide order canal none carry people thumb advice',
        long:26.0894,
        lat:22.6836,
    },
    {
        id:5,
        name:'Emilie Fuller',
        category:'sound',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'scale selection language corner remember sink realize lie hidden listen already glad finest company source hollow given took ride one pie family plate13.8002 north',
        long:98.2818,
        lat:95.9929,
    },
    {
        id:52,
        name:'Jean Russell',
        category:'fully',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'does back yard quietly blue castle while pig lonely replace pilot smallest leave because troops atomic wear price entirely section zoo gravity development wish',
        long:63.2872,
        lat:66.3341,
    },
    {
        id:21,
        name:'Jared Frank',
        category:'tie',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'branch climb indeed giving ran use screen dangerous necessary village goes play after ring themselves hearing seems lead program rocky slabs repeat plate44.7851s town',
        long:66.4478,
        lat:27.6259,
    },
    {
        id:34,
        name:'Eva Hall',
        category:'cold',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'me chain series like sort figure fox bow prove minute pick trick collect molecular far till its frame sleep taken passage finger name comfortable',
        long:45.695,
        lat:25.1119,
    },
    {
        id:46,
        name:'Johnny Ward',
        category:'glass',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'control draw alike forty continued recently jack am rose or curious contrast sets cat real experience themselves unusual memory picture perfect ought log wonder',
        long:74.8607,
        lat:28.2333,
    },
    {
        id:25,
        name:'Edward Newman',
        category:'fine',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'hard beautiful building generally describe buy further you needs down had general object something thin herd deer necessary camera beat simple eleven writer none',
        long:37.0049,
        lat:86.0372,
    },
    {
        id:100,
        name:'Phoebe Gordon',
        category:'eight',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'tropical share let farther nails has stock environment theory laid sat certain minute gentle damage citizen rather possibly hill tune only yes main would',
        long:35.7448,
        lat:40.2705,
    },
    {
        id:9,
        name:'Mittie Wilkins',
        category:'directly',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'corn ask square eventually garden sale trouble atom crop probably top explain shaking badly practical get door likely sky cheese easy rhyme sudden teeth',
        long:8.3755,
        lat:20.026,
    },
    {
        id:80,
        name:'Caleb Matthews',
        category:'first',
        image:'https://imagedelivery.net/5MYSbk45M80qAwecrlKzdQ/010ca3aa-4dd3-4d82-2abb-5fc558b2b500/preview',
        desc:'dust spite pencil cool soldier fly husband stiff gather pocket dead worry soon pretty locate west throw wise market appearance down group lungs above',
        long:87.031,
        lat:41.5271,
    },
]